# Generated by Django 3.1.4 on 2020-12-17 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(help_text='Somente números', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(help_text='xx/xx/xxxx'),
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.CharField(help_text='Digite os 10 Dígitos da conta', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banco_app.cliente')),
            ],
        ),
    ]
