# Generated by Django 3.1.4 on 2020-12-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_app', '0003_transacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='limite_conta',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=20),
        ),
        migrations.AddField(
            model_name='conta',
            name='saldo_conta',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
    ]
