# Generated by Django 3.1.4 on 2020-12-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_app', '0004_auto_20201221_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='conta',
            name='limite_conta',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=15),
        ),
        migrations.AlterField(
            model_name='conta',
            name='saldo_conta',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
        ),
    ]
